import Footer from "components/Footer"
import type { NextPage } from "next"
import Head from "next/head"
import React from "react"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>mirupapa profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>contents</main>

      <Footer />
    </div>
  )
}

export default Home
